### ISSUE TITLE
Question: definePage 中并没有在 this.data 赋值相关的属性，怎么做到能在 wxml 正确渲染的呢？

### ISSUE THREAD

**Issue by zouhangwithsweet** [vue-mini/vue-mini#10]

**Comment by yangmingshan** [comment]
setup() 返回的 state 会同步到 this.data 上，文档有[说明](https://vue-mini.github.io/guide/#%E5%AE%83%E6%98%AF%E5%A6%82%E4%BD%95%E5%B7%A5%E4%BD%9C%E7%9A%84)。
