### ISSUE TITLE
defineComponent 如果不写properties的话props会接受不到参数

### ISSUE THREAD

**Issue by Songyakang** [vue-mini/vue-mini#100]
是否可以不写这个properties, props依旧呢接收到这个参数呢?
![image](https://github.com/user-attachments/assets/29272fe3-eca0-4e43-a6ee-ac3e3332a1c9)

这是写了properties的, props可以接收到(倒不如说分析了依赖去挂载到了props上)
![WeChat40c056ef4b21ac5c2d38eaabb03b492c](https://github.com/user-attachments/assets/141ced82-7610-48ec-a15d-9da0ca3bea97)

**Comment by yangmingshan** [comment]
properties 是小程序的设计，必须声明。
