### ISSUE TITLE
不支持optionalTypes ts报错

### ISSUE THREAD

**Issue by MaZhaolin** [vue-mini/vue-mini#103]
<img width="696" alt="image" src="https://github.com/user-attachments/assets/cad71175-0097-4dde-92bc-3a7a7d7fe893">
<img width="745" alt="image" src="https://github.com/user-attachments/assets/6d6be484-c620-4087-a432-94bc7069a7fb">

**Comment by yangmingshan** [comment]
使用 optionalTypes 时，type 也是必须的。
