### ISSUE TITLE
如何在已有的项目中集成 vue-mini

### ISSUE THREAD

**Issue by jzsn2018** [vue-mini/vue-mini#109]
如何在已有的项目中集成 vue-mini

**Comment by yangmingshan** [comment]
你已有的项目是用原生写的吗？
最简单的方式就是从 GitHub 下载编译好的文件，直接用就好了。
https://vuemini.org/guide/quick-start.html#%E4%BB%8E-github-%E4%B8%8B%E8%BD%BD

**Comment by jzsn2018** [comment]
> 你已有的项目是用原生写的吗？ 最简单的方式就是从 GitHub 下载编译好的文件，直接用就好了。 https://vuemini.org/guide/quick-start.html#%E4%BB%8E-github-%E4%B8%8B%E8%BD%BD

直接当作一个依赖在 小程序中的 js 文件中使用吗？

**Comment by yangmingshan** [comment]
嗯，当自己的文件用就行。

**Comment by jzsn2018** [comment]
> 嗯，当自己的文件用就行。
感谢感谢，我试试看
