### ISSUE TITLE
很遗憾，只支持wechat，有跨平台的计划吗？

### ISSUE THREAD

**Issue by artiely** [vue-mini/vue-mini#12]

**Comment by yangmingshan** [comment]
跨平台包含两部分：一是支持其他平台，二是一次编写到处运行。

关于第一个问题，这个项目一开始就是计划支持不同平台的小程序的，只是按优先级先支持的微信小程序。

关于第二个问题，一次编写到处运行当然是所有人想要的，也包括我，但是考虑到不同平台的差异，可能不会那么顺利。这个还需要很多其他工作做前提，但是是努力的方向。
