### ISSUE TITLE
可以单独构建一个组件成为原生小程序组件与原生开发兼容吗？

### ISSUE THREAD

**Issue by Venusjason** [vue-mini/vue-mini#15]

**Comment by yangmingshan** [comment]
我不太能理解你的问题，可以再描述清楚一点吗？

---

我基于自己的理解尝试回答一下：Vue Mini 可以在一个组件中单独使用，与原生开发是兼容的。

**Comment by Venusjason** [comment]
> 我不太能理解你的问题，可以再描述清楚一点吗？
> 
> 我基于自己的理解尝试回答一下：Vue Mini 可以在一个组件中单独使用，与原生开发是兼容的。

>
> 是这个意思，可以单独做组件开发，使用编译后的组件与原生开发兼容

**Comment by YZWfinder** [comment]
只支持微信小程序，其他的小程序还没支持？

**Comment by yangmingshan** [comment]
@Venusjason 可以的，你甚至能在一个组件中混用 Vue Mini 和原生语法。

**Comment by yangmingshan** [comment]
> 只支持微信小程序，其他的小程序还没支持？

是的，目前仅支持微信小程序。

**Comment by yangmingshan** [comment]
我先把 issue 关了，如果你的问题没有被解答，可以继续追问。
