### ISSUE TITLE
全局inject

### ISSUE THREAD

**Issue by superlbr** [vue-mini/vue-mini#18]
虽然文档和console都提示说inject限于component.
但是从测试来看，从app. js provide是可以inject到page的，所以这个描述应该可以放开吧

**Comment by yangmingshan** [comment]
> 由于页面 onLoad 钩子会晚于所有子组件的 attached 钩子执行，所以 definePage 的 setup 函数会晚于所有子组件的 setup 函数执行。这在某些情况下（如：依赖注入）可能会造成问题，如果你需要 setup 函数按组件树从上到下依次执行，可以使用页面组件。

> Vue 的依赖注入是与组件树绑定的，但是由于小程序的限制我们不能访问组件树，所以 Vue Mini 的依赖注入与组件树并没有什么关系，每一项依赖都会被保存到一个全局单一的仓库中。也就是说依赖的 key 需要是全局唯一的，使用 Symbol 作 key 可以保证这一点。

以上均拷贝至文档，没有说仅限于 component，只是在 page 中使用 provide 可能会有问题，因为 page 的 setup 会晚于 component 的 setup 执行。

**Comment by yangmingshan** [comment]
可以贴一下 warning 内容吗？provide / inject 确实没有使用位置的限制。
