### ISSUE TITLE
怎么在项目中使用ui框架?

### ISSUE THREAD

**Issue by TaiAiAc** [vue-mini/vue-mini#20]
如题

**Comment by TaiAiAc** [comment]
我错了,我以后不问这种问题了,还好大佬没回复我,大佬得东西很厉害,感谢大佬,泪目

**Comment by yangmingshan** [comment]
与原生小程序一样，原生小程序怎么使用的 Vue Mini 中就怎么使用。

任何问题都是被欢迎的，只是我最近休假，回复不会很及时。
