### ISSUE TITLE
父组件如何触发子组件方法

### ISSUE THREAD

**Issue by Qinruiy** [vue-mini/vue-mini#28]
小程序的selectComponent 不能用。

**Comment by yangmingshan** [comment]
久等了～

你可以通过 `setup` 的第二个参数 `context` 来访问 `selectComponent`，[文档有写](https://vuemini.org/guide/component.html#:~:text=%E7%AC%AC%E4%BA%8C%E4%B8%AA%E5%8F%82%E6%95%B0%E6%8F%90%E4%BE%9B%E4%BA%86%E4%B8%80%E4%B8%AA%E4%B8%8A%E4%B8%8B%E6%96%87%E5%AF%B9%E8%B1%A1%EF%BC%8C%E4%BB%8E%E5%B0%8F%E7%A8%8B%E5%BA%8F%E7%BB%84%E4%BB%B6%20this%20%E4%B8%AD%E9%80%89%E6%8B%A9%E6%80%A7%E7%9A%84%E6%9A%B4%E9%9C%B2%E4%BA%86%E4%B8%80%E4%BA%9B%20property%E3%80%82)。

但是通常来说父组件直接调用子组件的方法是反模式，使用 `props` 或许更合适。
