### ISSUE TITLE
考虑升级下依赖

### ISSUE THREAD

**Issue by superlbr** [vue-mini/vue-mini#29]
vue 3.2发布了。。。

**Comment by yangmingshan** [comment]
计划中，只是最近工作比较忙，时间比较紧

**Comment by anyforever** [comment]
会不会用上了，中途此项目废弃了。。。@yangmingshan

**Comment by yangmingshan** [comment]
😅 你可以看看 Commits

**Comment by yangmingshan** [comment]
不过开源项目的长期健康开发、维护，一直是个头疼的问题（不止这个项目存在）。项目无法盈利，又需要投入大量的时间。我还有一份不算轻松的全职工作，这个项目跟我的工作又没什么关系。以上是客观事实，也是大多数开源作者所面临的困境。大多数人都是牺牲掉自己的休息时间，用❤️发电，长此以往确实不太健康。想办法让项目能带来收入，可能是唯一的出路。

所以大家愿意提供赞助吗？🤪

**Comment by GenesisChou** [comment]
贴个二维码吧，大伙不介意的

**Comment by yangmingshan** [comment]
哈哈，等我关掉这个 issue 再贴吧

**Comment by itmanyong** [comment]
> 尽管开源项目的长期、维护，一直是个头疼的（这个项目存在的）。项目不能承受健康，又需要大量的问题。以上是事实真相，也是大多数公开作者所用的牺牲。❤️想办法让项目能带来收入，可能是唯一的出路。
> 
> 所以大家愿意提供资助吗？🤪

乐意至极，很看好vue-moni的设计思维。赞助我相信作为开发人员都是很愿意的。

**Comment by yangmingshan** [comment]
久等了

https://github.com/vue-mini/vue-mini/releases/tag/0.3.0

**Comment by yangmingshan** [comment]
我开通了爱发电，可以通过爱发电周期性赞助我（需登录）
https://afdian.net/@yangmingshan

也可以通过支付宝或微信给我提供一次性赞助

![IMG_1803 (1)](https://user-images.githubusercontent.com/13585043/135259274-194f2f84-79f0-429c-9f59-a78a8543e3c1.jpg)

![IMG_1802 (1)](https://user-images.githubusercontent.com/13585043/135259286-0070f0d0-de9f-4582-9bb2-21654bdd243f.jpg)

**Comment by superlbr** [comment]
@vue/reactivity 锁了版本，可以更新吗?

**Comment by superlbr** [comment]
vue3.4 release啦

**Comment by yangmingshan** [comment]
在升了，在升了

**Comment by yangmingshan** [comment]
https://github.com/vue-mini/vue-mini/releases/tag/1.0.0-beta.1

**Comment by superlbr** [comment]
请问下小程序基础库版本最低要求提升为 v3.0.0，是因为哪里的变动？

**Comment by yangmingshan** [comment]
准确来说是 v2.25.1，但是大版本升级顺便把基础库提一个大版本也很合理

**Comment by superlbr** [comment]
基础库3.0覆盖率为91.74%，2.25有97.4%
92%跟98%还是差好多，这是能升级与不能升级的区别。。

**Comment by yangmingshan** [comment]
实际最低要求是 2.25.1，只是我写的 3.0.0

**Comment by superlbr** [comment]
嗯嗯

**Comment by superlbr** [comment]
请教下，啥时候1.0哈

**Comment by yangmingshan** [comment]
这个月。不会有大改动了，可以放心食用。

**Comment by superlbr** [comment]
create-vue-mini生成的项目里已经没有`promise-polyfill`，不需要兼容了是吧

**Comment by yangmingshan** [comment]
`promise-polyfill` 换地方了：https://github.com/vue-mini/create-vue-mini/commit/f4be36538c2e32d7cf3ac90b3a2400d69c8851e2

`regenerator-runtime` 升级 Babel 后不需要手动引入了

后面有新的问题麻烦到对应仓库下开新 issue 吧，就不要继续在这个 issue 聊了
