### ISSUE TITLE
咨询下此项目目前有长期维护的发展计划吗

### ISSUE THREAD

**Issue by itmanyong** [vue-mini/vue-mini#32]
如题，害怕如同kpi突然夭折了，想咨询下是否长期维护，很好看vue-mini的设计思想。
题外话：sao的脚手架初始化项目的tab图片阁下是从哪儿get的，感觉很细腻，想取下经

**Comment by yangmingshan** [comment]
> 如题，害怕如同kpi突然夭折了，想咨询下是否长期维护，很好看vue-mini的设计思想。

当然，主观上我肯定愿意长期维护，我也想花更多时间在这个项目上以改进文档、增强脚手架甚至提供 Vue SFC 支持等。现实情况我在 https://github.com/vue-mini/vue-mini/issues/29#issuecomment-918769004 也提到了，你也看到了，时间是比较有限的。希望此项目能慢慢带来一些收入，我也能投入更多的时间。当然即使它不能带来什么收入，我也计划长期维护，只是工作忙起来更新可能会比较慢。

> 题外话：sao的脚手架初始化项目的tab图片阁下是从哪儿get的，感觉很细腻，想取下经

我忘了，应该是在网上某个地方扒的，找图标可以试试这个项目👇
https://github.com/antfu/icones
