### ISSUE TITLE
reactive 不能添加属性吗？

### ISSUE THREAD

**Issue by DevinWell1ee** [vue-mini/vue-mini#39]
![image](https://user-images.githubusercontent.com/34705915/154839265-cdb473c9-e4d1-483d-86ab-a69f165bdde0.png)

还有一种情况，比如我一个数据开始可能为null, 然后一系列操作以后，返回一个对象 
![image](https://user-images.githubusercontent.com/34705915/154839311-f556cade-8118-4ce8-90c0-a6efe1b1f263.png)

**Comment by yangmingshan** [comment]
第一个是 TS 类型问题，如果类型推导不能满足你的需求，可以使用泛型手写类型。

第二个是错误用法，你需要使用 `ref`。

建议认真看一遍 Vue 3 的新文档：https://vuejs.org/
