### ISSUE TITLE
可以在文档中的 “比较” 章节提及一下与 didi/mpx 的区别吗？

### ISSUE THREAD

**Issue by ItsRyanWu** [vue-mini/vue-mini#41]
[didi/mpx](https://github.com/didi/mpx)
据我理解，两种都属于增强型而非强运行时依赖型框架，但 vue-mini 的特点在于借鉴 Vue 3 以及 composition api 的设计？

**Comment by yangmingshan** [comment]
我对 mpx 不熟，等我有空研究一下

**Comment by yangmingshan** [comment]
今天刚好在 GitHub 主页上看到了 Mpx，非常粗略的看了一下。确实如你所说，二者的设计哲学十分相似，可能最显著的区别就是 Mpx 是基于 Vue 2 的，Vue Mini 是基于 Vue 3 的。说的更底层一点，Mpx 的响应式数据是用 Object.defineProperty 实现的，Vue Mini 是直接使用的 Vue 3 基于 proxy 的响应式核心 @vue/reactivity

**Comment by yangmingshan** [comment]
已更新
https://vuemini.org/guide/comparisons.html#mpx
