### ISSUE TITLE
setup中如何使用setData更新data中数据

### ISSUE THREAD

**Issue by ChobitsSP** [vue-mini/vue-mini#43]
小程序中有些特殊组件 比如map中的markers,polyline 等属性
是无法使用setup返回的proxy对象绑定的 只能定义在data中
但是setup中方法无法使用setData方法 操作data中数据

希望setup里的context可以暴露出setData方法
或者context暴露出页面/组件中的方法
(这样可能会破坏封闭性 也许可以使用ts限制setData中的key?)

**Comment by yangmingshan** [comment]
> 小程序中有些特殊组件 比如map中的markers,polyline 等属性
是无法使用setup返回的proxy对象绑定的 只能定义在data中

听着不太对，setup 返回的数据最终也是设置到 data 中，它们没有区别。应该不存在你说的这种情况。

**Comment by yangmingshan** [comment]
你如果有进一步信息可以继续补充
