### ISSUE TITLE
优化 setData 调用频次

### ISSUE THREAD

**Issue by dhlolo** [vue-mini/vue-mini#55]
https://github.com/vue-mini/vue-mini/blob/2afe33981090539a031a689dc4743411dd4f1f59/packages/wechat/src/component.ts#L177

https://developers.weixin.qq.com/miniprogram/dev/framework/audits/performance.html#_4-setData%E8%B0%83%E7%94%A8%E9%A2%91%E7%8E%87

**Comment by yangmingshan** [comment]
watch 本身就有做批处理
https://github.com/vue-mini/vue-mini/blob/master/packages/wechat/src/watch.ts#L304

**Comment by dhlolo** [comment]
watch是分批的，但对底层setData的调用却依旧是最细颗粒的，问题不是出现在逻辑层，而是小程序逻辑层和视图层之间

**Comment by dhlolo** [comment]
不过作为玩具已经可以了

**Comment by yangmingshan** [comment]
> 不过作为玩具已经可以了

如果你认为 Vue Mini 是玩具，那我挺好奇你心中的非玩具是什么品质。

**Comment by yangmingshan** [comment]
我记得之前微信小程序开发文档有写，setData 本身有做批处理。但是现在看好像又没了，不知道是不是微信小程序改了。

**Comment by yangmingshan** [comment]
@SgLy 不好意思想请问一下，你知道微信小程序 setData 批处理的历史背景吗？

**Comment by dhlolo** [comment]
> > 不过作为玩具已经可以了
> 
> 如果你认为 Vue Mini 是玩具，那我挺好奇你心中的非玩具是什么品质。

首先回答问题：
- 很简单：可以支持企业级应用和迭代的。

然后，解释下：
- 其实小程序应用开发者们屎上雕花的年头多了(并不是说您的框架是屎，相反star也证明了大家对你工作的认可)，也慢慢习惯各种框架作者(包括微信官方团队)的冷漠和高傲。

最后，如果能保持开放包容，并且更进一步就再好不过了

**Comment by yangmingshan** [comment]
> 可以支持企业级应用和迭代的。

你深入思考过什么叫“企业级”吗？你怎么知道 Vue Mini 没有经历过”企业级“项目的考验？Vue Mini 的性能甩市面上所谓的“企业级”小程序框架几条街。

> 其实小程序应用开发者们屎上雕花的年头多了(并不是说您的框架是屎，相反star也证明了大家对你工作的认可)，也慢慢习惯各种框架作者(包括微信官方团队)的冷漠和高傲。

论高傲我怕是不及你，不知道的还以为是老师来点评学生的作业了呢。

提交 issue 前先学会怎么尊重、谦卑、友好的沟通吧。
