### ISSUE TITLE
[Feature] 希望可以增强工程化等基建体验

### ISSUE THREAD

**Issue by calandnong** [vue-mini/vue-mini#65]
### 期望功能描述

当前Vue Mini主要实现了JavaScript的核心部分，但在其他基础设施方面（如编译的脚手架工具、社区讨论环境、Awesome列表等）还不够完善。虽然个人用户使用没有问题，但在公司或团队推广时，存在一些差距。具体来说，团队合作和业务开发在技术选型时，主要的阻力在于工程化的拓展性、社区生态和方案的完整性。

### 具体需求

1. **工程化的拓展性**
   - **脚手架工具的抽象和可拓展性**：希望脚手架工具能够支持更多的自定义和扩展功能，例如集成当前官方还未支持的SFC（单文件组件）。
   - **开放脚手架工具的接口**：允许开发者根据自身需求进行二次开发和集成。

2. **社区生态**
   - **社区讨论环境**：建立一个活跃的社区讨论平台，方便开发者交流和分享经验。
   - **Awesome列表**：创建并维护一个Awesome列表，收集和展示优秀的插件、工具和项目示例。

3. **方案的完整性**
   - **支持列表**：列出当前和计划支持的功能和工具，方便开发者了解项目的现状和未来方向。
   - **社区贡献引导**：收集需求并制定计划，引导社区贡献，逐步完善项目的各个方面。

### 高优需求

目前最希望优先支持的是工程化的拓展性增强，特别是脚手架工具的抽象和可拓展性，这样也方便比如近期重点需求如less、sass、unocss等工具等引入使用。

### 期望的解决方案

1. **脚手架工具**
   - 提供详细的文档和示例，展示如何进行自定义和扩展。
   - 开放脚手架工具的接口，允许开发者根据自身需求进行二次开发。

2. **社区生态**
   - 创建一个官方的讨论平台（如Discord、Slack或论坛）。
   - 启动并维护一个Awesome列表，鼓励社区贡献和分享。

3. **方案的完整性**
   - 制定并公开项目的支持列表和开发计划。
   - 收集社区需求，定期更新计划，引导社区贡献。

### 其他信息

如果需要进一步讨论或提供更多信息，请随时联系我。感谢作者的努力和付出！

**Comment by yangmingshan** [comment]
谢谢你的反馈跟建议，内容很多，我一一回复。

> _脚手架工具的抽象和可拓展性：希望脚手架工具能够支持更多的自定义和扩展功能，例如集成当前官方还未支持的SFC（单文件组件）。_

这其实是两个问题。SFC 支持比较独立也比较复杂，需要较长的开发时间，不过我也在考虑有没有渐进支持的道路，这个请保持耐心。

至于脚手架工具的抽象和可拓展性，我就是考虑到开发者可能有不同的需求，所以现在 `create-vue-mini` 生成的项目都是零抽象的，构建脚本 `build.js` 都是完全开放给开发者的，方便开发者根据自己的需求定制修改。当然这也不是最优的，最好是将构建模块封装起来，但留出设计好的扩展接口。这也是接下来会探索的方向。

> _开放脚手架工具的接口：允许开发者根据自身需求进行二次开发和集成。_

上面回答了，现在开发者是可以根据自身需求进行二次开发的。

> _社区讨论环境：建立一个活跃的社区讨论平台，方便开发者交流和分享经验。_

我已经开了 [GitHub Discussions](https://github.com/vue-mini/vue-mini/discussions)，这个可以作为论坛，欢迎分享交流。另外 Vue Mini 有一个微信交流群，可以添加我的微信：y_mingshan，我拉你入群。

> _Awesome列表：创建并维护一个Awesome列表，收集和展示优秀的插件、工具和项目示例。_

这个还需要一段时间积累，目前生态还不太丰富。当然如果你知道什么优秀的周边，欢迎分享。也欢迎一起来建设这个新兴的社区。

> _支持列表：列出当前和计划支持的功能和工具，方便开发者了解项目的现状和未来方向。_

我会整理一个 Roadmap，让大家了解正在进行，以及将来计划的事情。

> _社区贡献引导：收集需求并制定计划，引导社区贡献，逐步完善项目的各个方面。_

这个是建立在 Roadmap 基础之上的，吸引更多的贡献者当然是最理想的，但是时间、能力以及热情三者兼具的人是很少的。当然我保持乐观的态度，将来肯定会有更多的人参与到这个项目中。

> _目前最希望优先支持的是工程化的拓展性增强，特别是脚手架工具的抽象和可拓展性，这样也方便比如近期重点需求如less、sass、unocss等工具等引入使用。_

就如我上面所说，现在扩展性是有的，不过你可能是想要内置的扩展性。内置 CSS 的扩展能力已经在计划中，近期就会开工。

> _创建一个官方的讨论平台（如Discord、Slack或论坛）_

这一点我也想大家给点建议。虽然现在有微信群和 [GitHub Discussions](https://github.com/vue-mini/vue-mini/discussions)，但二者各有各的问题，微信群太封闭都没办法公开邀请人，GitHub Discussions 实时性和活跃度又不高。Discord 是个不错的平台，但是在国内太冷门，还需要翻墙。大伙会用 Discord 吗？或者国内有没有什么好的 Discord 替代品呢？

**Comment by calandnong** [comment]
> 谢谢你的反馈跟建议，内容很多，我一一回复。
> 
> > _脚手架工具的抽象和可拓展性：希望脚手架工具能够支持更多的自定义和扩展功能，例如集成当前官方还未支持的SFC（单文件组件）。_
> 
> 这其实是两个问题。SFC 支持比较独立也比较复杂，需要较长的开发时间，不过我也在考虑有没有渐进支持的道路，这个请保持耐心。
> 
> 至于脚手架工具的抽象和可拓展性，我就是考虑到开发者可能有不同的需求，所以现在 `create-vue-mini` 生成的项目都是零抽象的，构建脚本 `build.js` 都是完全开放给开发者的，方便开发者根据自己的需求定制修改。当然这也不是最优的，最好是将构建模块封装起来，但留出设计好的扩展接口。这也是接下来会探索的方向。
> 
> > _开放脚手架工具的接口：允许开发者根据自身需求进行二次开发和集成。_
> 
> 上面回答了，现在开发者是可以根据自身需求进行二次开发的。
> 
> > _社区讨论环境：建立一个活跃的社区讨论平台，方便开发者交流和分享经验。_
> 
> 我已经开了 [GitHub Discussions](https://github.com/vue-mini/vue-mini/discussions)，这个可以作为论坛，欢迎分享交流。另外 Vue Mini 有一个微信交流群，可以添加我的微信：y_mingshan，我拉你入群。
> 
> > _Awesome列表：创建并维护一个Awesome列表，收集和展示优秀的插件、工具和项目示例。_
> 
> 这个还需要一段时间积累，目前生态还不太丰富。当然如果你知道什么优秀的周边，欢迎分享。也欢迎一起来建设这个新兴的社区。
> 
> > _支持列表：列出当前和计划支持的功能和工具，方便开发者了解项目的现状和未来方向。_
> 
> 我会整理一个 Roadmap，让大家了解正在进行，以及将来计划的事情。
> 
> > _社区贡献引导：收集需求并制定计划，引导社区贡献，逐步完善项目的各个方面。_
> 
> 这个是建立在 Roadmap 基础之上的，吸引更多的贡献者当然是最理想的，但是时间、能力以及热情三者兼具的人是很少的。当然我保持乐观的态度，将来肯定会有更多的人参与到这个项目中。
> 
> > _目前最希望优先支持的是工程化的拓展性增强，特别是脚手架工具的抽象和可拓展性，这样也方便比如近期重点需求如less、sass、unocss等工具等引入使用。_
> 
> 就如我上面所说，现在扩展性是有的，不过你可能是想要内置的扩展性。内置 CSS 的扩展能力已经在计划中，近期就会开工。
> 
> > _创建一个官方的讨论平台（如Discord、Slack或论坛）_
> 
> 这一点我也想大家给点建议。虽然现在有微信群和 [GitHub Discussions](https://github.com/vue-mini/vue-mini/discussions)，但二者各有各的问题，微信群太封闭都没办法公开邀请人，GitHub Discussions 实时性和活跃度又不高。Discord 是个不错的平台，但是在国内太冷门，还需要翻墙。大伙会用 Discord 吗？或者国内有没有什么好的 Discord 替代品呢？

感谢作者的耐心回答，哈哈，期待你的Roadmap！如你所说，那确实是希望有更多的内置的拓展性而非我们自己定义，因为当前build.js太open，可能不太好形成社区规范，或者换句话说是没有官方的约定背书的，build.js的内容将会变成一个垃圾桶，未来分享/升级都会变得困难。期待后面的规划出台！对于官方讨论平台这块，据我了解国内用discord的还是比较少数的，特别是小程序开发的用户，但是这个开发者群体其实更多的讨论是qq群/小程序官方社区，如果是选择国内平台的话，或许可以试试：https://www.imdodo.com/，或者自己构建一个社区平台，或者通过一些方式引流到GitHub Discussions，微信群的话，当前我已经在啦，id：猪宝的猪，哈哈

**Comment by watsonhaw5566** [comment]
@calandnong 你的 (Dodo)[https://www.imdodo.com/] 做的很不错啊，如果可以支持一下 mac 就更棒了，加油。

**Comment by FliPPeDround** [comment]
我有兴趣做一个基于vite-plugin的打包工具，可能会比目前的`build.js`观感上要好一点
但在一些具体的功能实现上，还需要一些详细的讨论

**Comment by yangmingshan** [comment]
> 我有兴趣做一个基于vite-plugin的打包工具，可能会比目前的`build.js`观感上要好一点 但在一些具体的功能实现上，还需要一些详细的讨论

欢迎尝试，并分享你的成果。

**Comment by yangmingshan** [comment]
#93
