### ISSUE TITLE
感觉和Rubic非常像，如官网和API，我用Rubic做了两个小程序，请问和它有啥区别

### ISSUE THREAD

**Issue by zhongxingdou** [vue-mini/vue-mini#66]

**Comment by yangmingshan** [comment]
你是指 https://github.com/JasKang/rubic 吗？
我第一次听说。刚刚还搜了一下。但确实如你所说，不仅是像，简直是一摸一样！

我问问作者看他怎么说吧。

**Comment by yangmingshan** [comment]
@zhongxingdou Rubic 是 Fork 的 Vue Mini，你还是换成 Vue Mini 吧
https://github.com/JasKang/rubic/issues/25

**Comment by yangmingshan** [comment]
`Rubic` 已经删库跑路了。

Issue 备份链接：
https://rubic.pages.dev
