### ISSUE TITLE
自定义tabbar使用defineComponent数据会有延迟

### ISSUE THREAD

**Issue by Songyakang** [vue-mini/vue-mini#68]
使用defineComponent 时, 不管是在setup里定义index还是在data里声明index, 切换页面后数据更新会在下一次点击事件里更新
![image](https://github.com/user-attachments/assets/040a8c7e-f433-413c-b905-82003be56969)

<img width="904" alt="image" src="https://github.com/user-attachments/assets/bbef4ddf-2e5f-42b0-9167-e2b915ba894d">

**Comment by Songyakang** [comment]
导航切换, 预期表现是点接口应该跳转mine/index. 并且选中状态应该是“接口”二字呈绿色选中状态, 世纪表现是我再点击“组件”才会把选中状态给到“接口”

**Comment by yangmingshan** [comment]
麻烦把你的模板也贴一下，最好能给个 repo

**Comment by xiaweiss** [comment]
@Songyakang 是你程序问题，自定义 tabbar 切换后，组件是重新加载的，也就是 data 都是默认值，并且重新执行 attatch 生命周期。你缺少了监听页面切换，并且设置高亮的逻辑。

**Comment by yangmingshan** [comment]
@Songyakang 如 @xiaweiss 所说，是你使用的不太对。

> 每个 tab 页下的自定义 tabBar 组件实例是不同的，可通过自定义组件下的 getTabBar 接口，获取当前页面的自定义 tabBar 组件实例。

> 注意：如需实现 tab 选中态，要在当前页面下，通过 getTabBar 接口获取组件实例，并调用 setData 更新选中态。

以上摘录自微信小程序文档：
https://developers.weixin.qq.com/miniprogram/dev/framework/ability/custom-tabbar.html

如果使用 Vue Mini，可以将选中状态定义在组件之外，以实现跨实例共享。

```js
const selected = ref(0)

defineComponent({
  setup() {
    const switchTab = () => {
      // ...
    }
    
    return {
      selected,
      switchTab,
    }
  }
})
```
