### ISSUE TITLE
setData 后如何再次 setData？

### ISSUE THREAD

**Issue by xiaweiss** [vue-mini/vue-mini#70]
小程序原生语法为

```javascript
this.setData({
  // ...
}, () => {
   // 可能延时 100ms
   this.setData({
     // ...
   })
})
```

目前 wx.nextTick 有 bug，在并行的情况下，很大概率触发不了，嵌套 setData 是比较安全的方式

主要场景为设置 dom 展示后的一些操作，例如测量 dom 的尺寸等等

这个场景，请问框架有什么语法支持吗？

**Comment by yangmingshan** [comment]
文档有写（这部分文档可能需要重新整理一下

https://vuemini.org/guide/faq.html#%E6%88%91%E9%9C%80%E8%A6%81%E5%9C%A8%E5%B0%8F%E7%A8%8B%E5%BA%8F%E6%B8%B2%E6%9F%93%E5%90%8E%E5%81%9A%E4%B8%80%E4%BA%9B%E6%93%8D%E4%BD%9C-%E5%B0%8F%E7%A8%8B%E5%BA%8F%E5%8E%9F%E7%94%9F%E8%AF%AD%E6%B3%95%E5%8F%AF%E4%BB%A5%E4%BD%BF%E7%94%A8-setdata-%E7%9A%84%E5%9B%9E%E8%B0%83-vue-mini-%E5%BA%94%E8%AF%A5%E6%80%8E%E4%B9%88%E5%86%99%E5%91%A2

**Comment by xiaweiss** [comment]
非常感谢

**Comment by yangmingshan** [comment]
如果有问题，请随时反馈
