### ISSUE TITLE
[docs] 更清楚的写明支持的平台

### ISSUE THREAD

**Issue by yangmingshan** [vue-mini/vue-mini#76]
### Discussed in https://github.com/vue-mini/vue-mini/discussions/75

<div type='discussions-op-text'>

<sup>Originally posted by **oxxzz** July 16, 2024</sup>
**至少明确一下标题或介绍**

看了一圈网站、文档，没发现任何针对性的小程序平台描述。现状是小程序 !== 微信小程序</div>

**Comment by flxy1028** [comment]
只支持微信小程序
