### ISSUE TITLE
第三方组件库如何使用

### ISSUE THREAD

**Issue by Nuyoahzsp** [vue-mini/vue-mini#79]
大佬，如何使用第三方组件库？
在json文件下导入不行，自己手动编译进dist文件里，一运行npm run dev又会把文件删掉，只有在ts文件中import才会编译进dist文件，但有些组件不能import啊。
我使用的是tdesign

**Comment by yangmingshan** [comment]
与 https://github.com/vue-mini/create-vue-mini/issues/10 重复。
