### ISSUE TITLE
setData 回调 中做操作要怎么弄呢

### ISSUE THREAD

**Issue by ximing** [vue-mini/vue-mini#8]
目前响应式API应该没有管setData，一个响应的变量被更改并更新到界面上之后，再去做一些事情要怎么实现呢

**Comment by yangmingshan** [comment]
目前没有很好的办法。可以说的具体一点吗？什么操作需要依赖界面更新呢？

小程序没有 DOM，必须依赖界面更新的操作应该是非常少的。

**Comment by ximing** [comment]
比如setData界面更新之后  querySelector 计算高度进行锚点

**Comment by yangmingshan** [comment]
如果能提供一个最小化案例会很有帮助

**Comment by yangmingshan** [comment]
从 v1.0.0-beta.4 开始，标记为 `flush: 'post'` 的观察器会在页面渲染后执行。这可以覆盖 setData 回调的用例。

```js
defineComponent({
  setup() {
    const show = ref(false)
    watch(show, () => {
      // 会在 show 变更触发的重渲染之后执行
      // ...
    }, { flush: 'post' })
    // ...
  }
})
```
