### ISSUE TITLE
希望文档增加一下怎么引入第三方npm包

### ISSUE THREAD

**Issue by jyrncl** [vue-mini/vue-mini#81]
希望文档增加一下怎么引入第三方npm包

**Comment by yangmingshan** [comment]
你是指纯 js 包，还是小程序组件库？

**Comment by jyrncl** [comment]
组件库，或者sass能引入吗

**Comment by yangmingshan** [comment]
组件库请跟踪这个 Issue: https://github.com/vue-mini/create-vue-mini/issues/10
Sass 请跟踪这个 Issue: https://github.com/vue-mini/create-vue-mini/issues/2

**Comment by yangmingshan** [comment]
[如何使用小程序组件库？](https://github.com/vue-mini/create-vue-mini?tab=readme-ov-file#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8%E5%B0%8F%E7%A8%8B%E5%BA%8F%E7%BB%84%E4%BB%B6%E5%BA%93)
