### ISSUE TITLE
希望支持.vue文件开发

### ISSUE THREAD

**Issue by Baiyuetribe** [vue-mini/vue-mini#83]
目前的运行时，感觉既然都是js，有点为何不用原生的困惑。
希望新增.vue文件支持，拥抱海量UI组件，实现真正的生产力。
![image](https://github.com/user-attachments/assets/2ab2cc28-292e-43b0-9717-bc57e027dc7d)

**Comment by yangmingshan** [comment]
与 #7 重复。
