### ISSUE TITLE
如何引入UI组件

### ISSUE THREAD

**Issue by Iden9** [vue-mini/vue-mini#84]

**Comment by yangmingshan** [comment]
与 https://github.com/vue-mini/create-vue-mini/issues/10 重复

**Comment by yangmingshan** [comment]
[如何使用小程序组件库？](https://github.com/vue-mini/create-vue-mini?tab=readme-ov-file#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8%E5%B0%8F%E7%A8%8B%E5%BA%8F%E7%BB%84%E4%BB%B6%E5%BA%93)
