### ISSUE TITLE
目前Vue Mini可以使用哪些组件库

### ISSUE THREAD

**Issue by zoujinglong666** [vue-mini/vue-mini#86]
目前Vue Mini可以使用哪些组件库

**Comment by yangmingshan** [comment]
小程序组件库都可以用，只是要等 https://github.com/vue-mini/create-vue-mini/issues/10

**Comment by yangmingshan** [comment]
[如何使用小程序组件库？](https://github.com/vue-mini/create-vue-mini?tab=readme-ov-file#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8%E5%B0%8F%E7%A8%8B%E5%BA%8F%E7%BB%84%E4%BB%B6%E5%BA%93)
