### ISSUE TITLE
优化热更新问题

### ISSUE THREAD

**Issue by zoujinglong666** [vue-mini/vue-mini#87]
<img width="984" alt="image" src="https://github.com/user-attachments/assets/96a918b9-9495-479c-bb85-033d2c76e455">
一开始执行pnpm dev都是正常 后面不小心将pnpm dev关闭掉再进行启动该命令 就显示以上画面 我实际该文件代码是这个 
![Uploading image.png…]()

**Comment by yangmingshan** [comment]
我只看到一张你 IDE 的截图

**Comment by yangmingshan** [comment]
重启你的 IDE 试试
