### ISSUE TITLE
微信开发者工具导入项目报错问题 app.js

### ISSUE THREAD

**Issue by zoujinglong666** [vue-mini/vue-mini#88]
<img width="1230" alt="image" src="https://github.com/user-attachments/assets/67c86da1-5078-4361-bbd0-ee3c1ee570fb">
我看文档是直接将相应项目导入到微信开发者工具 后面发现保存  就直接使用dist目录进行导入到微信开发者工具这也是正常 无需更改配置文件 也能正常热更新  直接导入项目 会爆错  也有可能是我的使用方法不太正确

**Comment by yangmingshan** [comment]
应该是你使用的问题，仅凭截图我很难帮上忙。
