### ISSUE TITLE
Vue-mini对Vue生态的UI组件的支持？

### ISSUE THREAD

**Issue by geextudio** [vue-mini/vue-mini#89]
Vue-mini开发微信小程序时，对Vue生态的UI组件的支持改如何集成？还是说只能使用微信原生组件，或者支持集成一些主打移动web或者小程序的UI组件，比如[NutUI](https://nutui.jd.com/3x/#/)?

**Comment by yangmingshan** [comment]
只能用小程序组件库，如：

Vant: https://vant.pro/vant-weapp
TDesign: https://tdesign.tencent.com/miniprogram
