### ISSUE TITLE
 小程序 不支持v3.0.0 以下版本的原因是什么？

### ISSUE THREAD

**Issue by corzero** [vue-mini/vue-mini#90]
小程序 不支持 v3.0.0 以下版本的原因是什么？是相关api无法使用么？哪些api无法使用呢？

**Comment by yangmingshan** [comment]
https://vuemini.org/guide/compatibility.html#%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8F%E5%9F%BA%E7%A1%80%E5%BA%93
