### ISSUE TITLE
TypeError: (intermediate value).resolve is not a function

### ISSUE THREAD

**Issue by zhuzaiBro** [vue-mini/vue-mini#96]
new URL(import.meta.resolve(`${name}/package.json`)),
                        ^

TypeError: (intermediate value).resolve is not a function

Node.js v18.17.0

**Comment by yangmingshan** [comment]
> 已安装 >= 18.19.1 < 19 或 >= 20.6.1 版本的 Node.js

https://vuemini.org/guide/quick-start.html

**Comment by zhuzaiBro** [comment]
thanks!
